import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Auto-generated sidebars per top-level section.
 * Order within each section is controlled by `sidebar_position` frontmatter
 * or `_category_.json` files — not by this file.
 *
 * To add a new section: add a category here pointing at the new dirName.
 * To add a new doc: just create the .md file — it appears automatically.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [{ type: 'autogenerated', dirName: '01-getting-started' }],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [{ type: 'autogenerated', dirName: '02-concepts' }],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [{ type: 'autogenerated', dirName: '03-guides' }],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [{ type: 'autogenerated', dirName: '04-operations' }],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{ type: 'autogenerated', dirName: '05-reference' }],
    },
    {
      type: 'category',
      label: 'Resources',
      items: [{ type: 'autogenerated', dirName: '06-resources' }],
    },
    {
      type: 'category',
      label: 'CLI',
      items: [{ type: 'autogenerated', dirName: '07-cli' }],
    },
    {
      type: 'category',
      label: 'MCP Servers',
      items: [{ type: 'autogenerated', dirName: '08-mcp' }],
    },
    {
      type: 'category',
      label: 'Experience Engine',
      items: [{ type: 'autogenerated', dirName: '09-experience-engine' }],
    },
  ],
};

export default sidebars;
